<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EtwScaffolding\Module'                        => __DIR__ . '/Module.php',
    'EtwScaffolding\Controller\IndexController' => __DIR__ . '/src/EtwScaffolding/Controller/IndexController.php',
    'EtwScaffoldingTest\Framework\TestCase'        => __DIR__ . '/tests/EtwScaffolding/Framework/TestCase.php',
    'EtwScaffoldingTest\SampleTest'                => __DIR__ . '/tests/EtwScaffolding/SampleTest.php',
);
